/************** TABLESPACE CREATION SCRIPT **************/

CREATE TABLESPACE EVISOR_TS DATAFILE '/home/oracle/oradata/eVisor/auditoria/EVISOR_TS_000001.ora' SIZE 1024M AUTOEXTEND ON; 

/************** USER OWNER CREATION *****************/

/* EVISOROWNER */

CREATE USER "EVISOROWNER"  PROFILE "DEFAULT" 
    IDENTIFIED BY "XXXXXXXX" DEFAULT TABLESPACE "EVISOR_TS" 
        ACCOUNT UNLOCK;
	GRANT ALTER ANY TABLE TO "EVISOROWNER";
	GRANT CREATE ANY TABLE TO "EVISOROWNER";
	GRANT DROP ANY TABLE TO "EVISOROWNER";
	GRANT "RESOURCE" TO "EVISOROWNER";
	GRANT "CONNECT" TO "EVISOROWNER";

COMMIT;
EXIT;

