/********************************************************/
/************** INSERTING CONSTANTS      *******************/
/********************************************************/

/** ALARMS **/

/** DIRECCION DE CORREO POR DEFECTO PARA LAS ALARMAS PRODUCIDAS**/
INSERT INTO RECEIVERS VALUES (SQ_RECEIVERS.NEXTVAL,'<mail_administrador>');

/** ALARMA DE ACCESO A BASE DE DATOS **/
INSERT INTO ALARM VALUES ('ALARM_001','AL_D_001','AL_S_001','AL_M_001','N',15,SYSDATE);

INSERT INTO ALARM_REC VALUES ('ALARM_001',SQ_RECEIVERS.CURRVAL);

/** ALARMA DE ACCESO AL SERVIDOR DE @firma **/
INSERT INTO ALARM VALUES ('ALARM_002','AL_D_002','AL_S_002','AL_M_002','N',15,SYSDATE);

INSERT INTO ALARM_REC VALUES ('ALARM_002',SQ_RECEIVERS.CURRVAL);

/** ALARMA DE ACCESO AL SERVIDOR OPEN OFFICE **/
INSERT INTO ALARM VALUES ('ALARM_003','AL_D_003','AL_S_003','AL_M_003','N',15,SYSDATE);

INSERT INTO ALARM_REC VALUES ('ALARM_003',SQ_RECEIVERS.CURRVAL);

/** SERVICIOS DE AUDITORIA **/

INSERT INTO SERVICES VALUES (0, 'AUD_S_000');

INSERT INTO SERVICES VALUES (1, 'AUD_S_001');

/** OPERACIONES DE AUDITORIA **/

INSERT INTO ACTIONTYPES VALUES (0, 'AUD_OP_000');

INSERT INTO ACTIONTYPES VALUES (1, 'AUD_OP_001');

INSERT INTO ACTIONTYPES VALUES (2, 'AUD_OP_002');

INSERT INTO ACTIONTYPES VALUES (3, 'AUD_OP_003');

INSERT INTO ACTIONTYPES VALUES (4, 'AUD_OP_004');

INSERT INTO ACTIONTYPES VALUES (5, 'AUD_OP_005');

INSERT INTO ACTIONTYPES VALUES (6, 'AUD_OP_006');

INSERT INTO ACTIONTYPES VALUES (7, 'AUD_OP_007');

INSERT INTO ACTIONTYPES VALUES (8, 'AUD_OP_008');

/** CAMPOS DE LAS TRAZAS DE AUDITORIA **/

INSERT INTO FIELDS VALUES (0,'APP_ID','AUD_F_000');

INSERT INTO FIELDS VALUES (1,'REQ_ID','AUD_F_001');

INSERT INTO FIELDS VALUES (2,'RES_ID','AUD_F_002');

INSERT INTO FIELDS VALUES (3,'TEMPL_ID','AUD_F_003');

INSERT INTO FIELDS VALUES (4,'IS_SIGN','AUD_F_004');

INSERT INTO FIELDS VALUES (5,'EXT_SIGN','AUD_F_005');

INSERT INTO FIELDS VALUES (6,'EXT_DOC','AUD_F_006');

INSERT INTO FIELDS VALUES (7,'BARCODES','AUD_F_007');

INSERT INTO FIELDS VALUES (8,'EXT_PARAMS','AUD_F_008');

INSERT INTO FIELDS VALUES (9,'RES_CODE','AUD_F_009');

INSERT INTO FIELDS VALUES (10,'RES_MSG','AUD_F_010');

INSERT INTO FIELDS VALUES (11,'RES_CAUSE','AUD_F_011');

INSERT INTO FIELDS VALUES (12,'UO_ID','AUD_F_012');

INSERT INTO FIELDS VALUES (13,'TEMP_TYPE','AUD_F_013');

/** ADMINISTRATOR USER DATA **/
INSERT INTO PERSONALDATA VALUES ( SQ_PERSONAL.NEXTVAL,'<NOMBRE_ADMINISTRADOR>','<APELLIDOS_ADMINISTRADOR>',<NUMERO_DE_TELEFONO>,'<MAIL>',SYSDATE,null);
	
INSERT INTO USERS VALUES (SQ_USERS.NEXTVAL,'Admin','0DPiKuNIrrVmD8IUCuw1hQxNqZc=',SQ_PERSONAL.CURRVAL,'N',SYSDATE,null);
	
/** UO **/
INSERT INTO UO VALUES (SQ_UO.NEXTVAL,'ROOT','ROOT',SYSDATE,null);

/** ATTACHMENT TABLE VALUES **/
INSERT INTO ATTACHMENT VALUES (1,'N','N','N','N','N');
INSERT INTO ATTACHMENT VALUES (2,'N','Y','N','N','N');
INSERT INTO ATTACHMENT VALUES (3,'N','Y','Y','N','N');
INSERT INTO ATTACHMENT VALUES (4,'N','Y','Y','Y','N');
INSERT INTO ATTACHMENT VALUES (5,'Y','Y','Y','Y','N');
INSERT INTO ATTACHMENT VALUES (6,'Y','N','Y','Y','N');
INSERT INTO ATTACHMENT VALUES (7,'Y','N','N','Y','N');
INSERT INTO ATTACHMENT VALUES (8,'Y','N','N','N','N');
INSERT INTO ATTACHMENT VALUES (9,'Y','N','Y','N','N');
INSERT INTO ATTACHMENT VALUES (10,'N','Y','N','Y','N');
INSERT INTO ATTACHMENT VALUES (11,'Y','Y','N','N','N');
INSERT INTO ATTACHMENT VALUES (12,'Y','Y','N','Y','N');
INSERT INTO ATTACHMENT VALUES (13,'N','N','Y','Y','N');
INSERT INTO ATTACHMENT VALUES (14,'N','N','Y','N','N');
INSERT INTO ATTACHMENT VALUES (15,'Y','Y','Y','N','N');
INSERT INTO ATTACHMENT VALUES (16,'N','N','N','Y','N');
INSERT INTO ATTACHMENT VALUES (17,'N','N','N','N','Y');
INSERT INTO ATTACHMENT VALUES (18,'N','Y','N','N','Y');
INSERT INTO ATTACHMENT VALUES (19,'N','Y','Y','N','Y');
INSERT INTO ATTACHMENT VALUES (20,'N','Y','Y','Y','Y');
INSERT INTO ATTACHMENT VALUES (21,'Y','Y','Y','Y','Y');
INSERT INTO ATTACHMENT VALUES (22,'Y','N','Y','Y','Y');
INSERT INTO ATTACHMENT VALUES (23,'Y','N','N','Y','Y');
INSERT INTO ATTACHMENT VALUES (24,'Y','N','N','N','Y');
INSERT INTO ATTACHMENT VALUES (25,'Y','N','Y','N','Y');
INSERT INTO ATTACHMENT VALUES (26,'N','Y','N','Y','Y');
INSERT INTO ATTACHMENT VALUES (27,'Y','Y','N','N','Y');
INSERT INTO ATTACHMENT VALUES (28,'Y','Y','N','Y','Y');
INSERT INTO ATTACHMENT VALUES (29,'N','N','Y','Y','Y');
INSERT INTO ATTACHMENT VALUES (30,'N','N','Y','N','Y');
INSERT INTO ATTACHMENT VALUES (31,'Y','Y','Y','N','Y');
INSERT INTO ATTACHMENT VALUES (32,'N','N','N','Y','Y');

/** KEYSTORE TABLE VALUES **/
INSERT INTO KEYSTORE VALUES (1,'AUTORIZACION WS',1);
INSERT INTO KEYSTORE VALUES (2,'CONFIANZA SSL',1);
INSERT INTO KEYSTORE VALUES (3,'CONFIANZA SOAP',1);
INSERT INTO KEYSTORE VALUES (4,'KEYSTORE SOAP',1);

COMMIT;

EXIT;