<wsdl:definitions xmlns:apachesoap="http://xml.apache.org/xml-soap"
	xmlns:impl="http://localhost:8089/eVisorToPdfWS/services/ExportToPDFService"
	xmlns:intf="http://localhost:8089/eVisorToPdfWS/services/ExportToPDFService"
	xmlns:soapenc="http://schemas.xmlsoap.org/soap/encoding/" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
	xmlns:wsdlsoap="http://schemas.xmlsoap.org/wsdl/soap/" xmlns:xsd="http://www.w3.org/2001/XMLSchema"
	targetNamespace="http://localhost:8089/eVisorToPdfWS/services/ExportToPDFService">
	<!-- WSDL created by Apache Axis version: 1.4 Built on Apr 22, 2006 (06:55:48 
		PDT) -->
	<wsdl:message name="exportToPDFResponse">
		<wsdl:part name="exportToPDFReturn" type="soapenc:base64Binary" />
	</wsdl:message>
	<wsdl:message name="exportToPDFRequest">
		<wsdl:part name="document" type="soapenc:base64Binary" />
	</wsdl:message>
	<wsdl:portType name="ExportToPDFService">
		<wsdl:operation name="exportToPDF" parameterOrder="document">
			<wsdl:input message="impl:exportToPDFRequest" name="exportToPDFRequest" />
			<wsdl:output message="impl:exportToPDFResponse" name="exportToPDFResponse" />
		</wsdl:operation>
	</wsdl:portType>
	<wsdl:binding name="ExportToPDFServiceSoapBinding" type="impl:ExportToPDFService">
		<wsdlsoap:binding style="rpc"
			transport="http://schemas.xmlsoap.org/soap/http" />
		<wsdl:operation name="exportToPDF">
			<wsdlsoap:operation soapAction="" />
			<wsdl:input name="exportToPDFRequest">
				<wsdlsoap:body encodingStyle="http://schemas.xmlsoap.org/soap/encoding/"
					namespace="http://ws.evisortopdfws.signaturereport.gob.es" use="encoded" />
			</wsdl:input>
			<wsdl:output name="exportToPDFResponse">
				<wsdlsoap:body encodingStyle="http://schemas.xmlsoap.org/soap/encoding/"
					namespace="http://ws.evisortopdfws.signaturereport.gob.es" use="encoded" />
			</wsdl:output>
		</wsdl:operation>
	</wsdl:binding>
	<wsdl:service name="ExportToPDFServiceService">
		<wsdl:port binding="impl:ExportToPDFServiceSoapBinding"
			name="ExportToPDFService">
			<wsdlsoap:address
				location="http://localhost:8096/eVisorToPdfWS/services/ExportToPDFService" />
		</wsdl:port>
	</wsdl:service>
</wsdl:definitions>